checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - spec/*

build:
    environment:
        variables:
            COMPOSER_MEMORY_LIMIT: -1
    dependencies:
        before:
            - sudo apt-get install -y php-xdebug
