language: php

php:
    - 7.2

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar update --prefer-dist --ignore-platform-reqs

script: bin/phpspec run -fpretty --verbose

cache:
    directories:
        - $HOME/.composer/cache

after_script:
    - php bin/php-coveralls -v
